spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 587
    username: 6a8ce87d149569
    password: 7d91cc06d7b24a
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  freemarker:
    template-loader-path: 'classpath:/templates'

logging:
  level:
    org.zalando.logbook: trace
---

spring:
  config:
    activate:
      on-profile: prod
      name: prod-YAML
      environment: production
      enabled: true
      servers:
        - www.abc.com
        - www.xyz.com
  datasource:
    url: 'jdbc:postgresql://localhost:5432/spring'
    username: postgres
    password: postgres
    driver-class-name: 'org.postgresql.Driver'

---

spring:
  config:
    activate:
      on-profile: test
      name: test-YAML
      environment: testing
      enabled: false
      servers:
        - www.abc.test.com
        - www.xyz.test.com
  datasource:
    url: 'jdbc:h2:mem:~'
    username: user
    password: 123
    driver-class-name: 'org.h2.Driver'
